### ISSUE TITLE
Release crashes when using circuits_gpio with releases.exs

### ISSUE THREAD

**Issue by glottis** [elixir-circuits/circuits_gpio#138]
Hello, this might not really be an issue per say but making a release on rpi zero w with a releases.exs makes for a fun crash:

> Erlang/OTP 23 [erts-11.1.8] [source] [smp:1:1] [ds:1:1:10] [async-threads:1]
> 2023-01-09 22:08:28.764197 ~s~n
>  "driver_select(0xb6200918, 0, ERL_DRV_READ ERL_DRV_USE, 1) by fd (0/1) driver #Port<0.13> stealing control of fd=0 from input driver tcp_inet #Port<0.8> \n"
>  =ERROR REPORT==== 9-Jan-2023::22:08:28.764197 ===
> driver_select(0xb6200918, 0, ERL_DRV_READ ERL_DRV_USE, 1) by fd (0/1) driver #Port<0.13> stealing control of fd=0 from input driver tcp_inet #Port<0.8>

This caused me quite the trouble for a couple of days. The use of releases.exs came from running raspian buster and an older elixir version on the pi.

Solution was like in https://github.com/elixir-circuits/circuits_gpio/issues/78 to remove the releases.exs file.

**Comment by fhunleth** [comment]
Sorry about not figuring anything out on this.

I'm closing since so much code has changed in the v2.0.0-pre* releases and `release.exs` got replaced with `runtime.exs`.

If anyone stumbbles on a similar looking error, could you open a new issue?
