### ISSUE TITLE
Rename set_edge_mode

### ISSUE THREAD

**Issue by fhunleth** [elixir-circuits/circuits_gpio#21]
`set_edge_mode/3` is feeling like it may not be the best name any more and I'm having mixed feelings about having both a keyword list and a default edge mode argument. What do others think?

To get things started, how about:

`set_interrupts(ref, enabled, options \\ [])`

where `enabled` is `true` or `false`. Options are:

* `edge` - `rising`, `falling`, or `both`. The default is `both`
* `suppress_glitches` - `true` or `false`. The default is `true`.
* `receiver` - pid/name of where to send notification messages. The default is `self()`

**Comment by mdsebald** [comment]
Maybe.  My thinking was that one purpose of `set_edge_mode()` or 'set_interrupt()`  is to set the edge dev virtual file to one of those 4 valid values, and I didn't think of that as an option, but rather a main parameter.  Adding level-triggered selections, feels like we're getting into the area of options.   I still agree with changing the function name.  I don't have a strong feeling about the name of the of the parameter, but I like the one-to-one match of the value of that parameter, and the set of allowed values for the edge file.

**Comment by fhunleth** [comment]
Yeah, I agree with options vs. mandatory. Currently the trigger mode is an optional parameter. I suspect that we're in agreement that that should change. Are we closing in on:

`set_interrupts(ref, trigger, options \\ [])`

I'm fine with keeping trigger as `none`, `rising`, `falling` and `both` like it currently is.
