### ISSUE TITLE
Look up registered names when sending notifications

### ISSUE THREAD

**Issue by fhunleth** [elixir-circuits/circuits_gpio#22]
Currently, registered process names are supported, but the name-to-pid translation happens when interrupts are enabled. To handle the case where the registered process dies and comes back, the lookup really should happen on the send call. This involves changes to the NIF.

**Comment by mdsebald** [comment]
OK. I see `erl_nif` has an `enif_whereis_pid()` function.  So the only downside is adding logic to determine if that should be called, on each interrupt.  Probably not a big deal.

**Comment by fhunleth** [comment]
We're not addressing this in v2. 

This may not be an issue since the idiom for using Circuits.GPIO for inputs is to open the GPIO in the process handling the notifications. That makes it easier to give the guarantees to the receiving process that the GPIO is set up correctly and hasn't crashed or anything like that.
